version: "2"
services:
  elasticsearch:
    build: .
    image: interaction/elasticsearch-icu:local
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
