name: Continuous Integration

on:
  push:
  schedule:
    - cron:  '0 17 * * *'  # 3 AM AEST

jobs:
  image:
    runs-on:
      - ${{ matrix.arch }}
      - linux
      - self-hosted
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.version }}/Dockerfile
          no-cache: ${{ github.event_name == 'schedule' }}
          push: true
          tags: ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:sha-${{ github.sha }}-${{ matrix.version }}-${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - arm64
          - x64
        version:
          - 7

  manifest:
    env:
      IMAGE_REPO: ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}
      IMAGE_TAG: sha-${{ github.sha }}-${{ matrix.version }}
    needs: image
    runs-on:
      - linux
      - self-hosted
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push branch manifest list
        run: |
          docker buildx imagetools create -t \
            ${{ env.IMAGE_REPO }}:${GITHUB_REF#refs/heads/}-${{ matrix.version }} \
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}-arm64 \
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}-x64
      - name: Push SHA manifest list
        run: |
          docker buildx imagetools create -t \
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }} \
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}-arm64 \
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}-x64
      - name: Push version manifest list
        if: github.ref == 'refs/heads/master'
        run: |
          # Version.
          docker buildx imagetools create -t \
            ${{ env.IMAGE_REPO }}:${{ matrix.version }} \
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}-arm64 \
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}-x64
      - name: Push 'latest' manifest list
        if: github.ref == 'refs/heads/master' && matrix.version == '7'
        run: |
          # Latest.
          docker buildx imagetools create -t \
            ${{ env.IMAGE_REPO }}:latest \
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}-arm64 \
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}-x64
      - name: Remove arch tags
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKER_PASSWORD }}"}' "https://hub.docker.com/v2/users/login/" | jq -r '.token')
          curl "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}/tags/${{ env.IMAGE_TAG }}-arm64/" -X DELETE -H "Authorization: JWT ${TOKEN}"
          curl "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}/tags/${{ env.IMAGE_TAG }}-x64/" -X DELETE -H "Authorization: JWT ${TOKEN}"
    strategy:
      matrix:
        version:
          - 7

  image-x64:
    env:
      IMAGE_REPO: ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}
      IMAGE_TAG: sha-${{ github.sha }}-${{ matrix.version }}
    runs-on:
      - linux
      - self-hosted
      - x64
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.version }}/Dockerfile
          no-cache: ${{ github.event_name == 'schedule' }}
          push: true
          tags: ${{ env.IMAGE_REPO }}:sha-${{ env.IMAGE_TAG }}
      - name: Push branch tag
        run: |
          docker tag ${{ env.IMAGE_REPO }}:sha-${{ env.IMAGE_TAG }} ${{ env.IMAGE_REPO }}:${GITHUB_REF#refs/heads/}-${{ matrix.version }}
          docker push ${{ env.IMAGE_REPO }}:${GITHUB_REF#refs/heads/}-${{ matrix.version }}
      - name: Push version tag
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag ${{ env.IMAGE_REPO }}:sha-${{ env.IMAGE_TAG }} ${{ env.IMAGE_REPO }}:${{ matrix.version }}
          docker push ${{ env.IMAGE_REPO }}:${{ matrix.version }}
    strategy:
      matrix:
        version:
          - 1
          - 1-alpine
          - 2.4
          - 2.4-alpine
          - 5
          - 5-alpine
          - 6

  readme:
    needs: manifest
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}
